-- 1. Create Table
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    price NUMERIC,
    price_info TEXT DEFAULT '/mes',
    grades TEXT,
    schedule_summary TEXT,
    schedule_details JSONB DEFAULT '[]'::jsonb,
    place TEXT,
    spots INTEGER DEFAULT 0,
    image_url TEXT,
    color TEXT DEFAULT 'bg-primary',
    category_icon TEXT,
    is_stem_approved BOOLEAN DEFAULT FALSE,
    important_note TEXT
);

-- 2. Enable RLS
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- 3. Policies
-- Drop existing to avoid conflicts if re-running
DROP POLICY IF EXISTS "Public read access" ON public.activities;
DROP POLICY IF EXISTS "Authenticated full access" ON public.activities;

CREATE POLICY "Public read access" ON public.activities 
    FOR SELECT USING (true);

CREATE POLICY "Authenticated full access" ON public.activities 
    FOR ALL USING (auth.role() = 'authenticated');

-- 4. Storage Bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('activity-images', 'activity-images', true)
ON CONFLICT (id) DO NOTHING;

-- 5. Storage Policies
DROP POLICY IF EXISTS "Public View Activity Images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Manage Activity Images" ON storage.objects;

CREATE POLICY "Public View Activity Images" ON storage.objects
    FOR SELECT USING (bucket_id = 'activity-images');

CREATE POLICY "Authenticated Manage Activity Images" ON storage.objects
    FOR ALL USING (bucket_id = 'activity-images' AND auth.role() = 'authenticated');

-- 6. Seed Data
INSERT INTO public.activities (
    title, category, price, price_info, schedule_summary, grades, image_url, color, 
    description, place, spots, schedule_details, important_note, category_icon, is_stem_approved
) VALUES 
(
    'Workshop de Robòtica: Build & Code',
    'Educatiu',
    45,
    '/mes',
    'Dilluns i Dimecres, 17:00h - 18:30h',
    '3r - 6è',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBty-h_7V34ad49vb7FikyDIYSI4rGKe2zAzOheIcYzxTH4cwe4q2o8wsEI6tp3xHK51pd15dbZUq2ZCroTnn-U910ntw7njr91F2CmdrzE6Dfm-nq3w2TCmqWMMH4OC9O2u6WZYGsCjdcSphdAGzqWm8HgVCeYvTcsV_xiLj-IAQ-6gnCt8z5tXUg9Y1e32WrzgDFsPjtI5Uv8VDP7-euChlnblBVOBLDgMoVAx3QocFKXXGVptJVB9G_xF9pacvPzrwltTz6vPp8',
    'bg-primary',
    'Uneix-te al nostre taller pràctic de robòtica on els alumnes aprenen els fonaments de l''enginyeria i la programació. Els participants treballaran en equips per dissenyar, construir i codificar els seus propis robots utilitzant kits de LEGO Education.',
    'Laboratori de l''Escola',
    12,
    '[{"group": "Grup A", "days": "Dll i Dmc", "time": "17:00 — 18:30"}, {"group": "Grup B", "days": "Dtm i Djs", "time": "17:00 — 18:30"}]'::jsonb,
    'Tots els alumnes han de portar la seva pròpia tauleta si volen guardar els seus projectes localment.',
    'school',
    true
),
(
    'Teatre Musical en Anglès',
    'Artística',
    30,
    '/mes',
    'Dimarts, 16:30h - 18:00h',
    'Infantil',
    'https://images.unsplash.com/photo-1503095392237-fc558db96328?auto=format&fit=crop&q=80&w=1000',
    'bg-pink-500',
    'Una combinació única d''expressió corporal, cant i aprenentatge de l''anglès a través de les arts escèniques. Els nens i nenes desenvolupen la seva confiança mentre es diverteixen interpretant els seus musicals preferits.',
    'Gimnàs de l''Escola',
    5,
    '[{"group": "Infantil 3-5", "days": "Dimarts", "time": "16:30 — 18:00"}]'::jsonb,
    'Es recomana portar roba còmoda i mitjons antilliscants.',
    'theater_comedy',
    false
),
(
    'Marxa-Marxa en Anglès',
    'Idiomes',
    30,
    '/mes',
    'Dijous, 16:30h - 18:00h',
    'Infantil',
    'https://images.unsplash.com/photo-1577896334614-201901ddde56?auto=format&fit=crop&q=80&w=1000',
    'bg-purple-500',
    'Aprenentatge actiu de l''anglès mitjançant jocs, música i moviment. Una forma natural i divertida d''introduir la llengua anglesa als més petits.',
    'Aula 1',
    8,
    '[{"group": "Infantil", "days": "Dijous", "time": "16:30 — 18:00"}]'::jsonb,
    null,
    'translate',
    false
),
(
    'Timbals',
    'Música',
    30,
    '/mes',
    'Divendres, 17:30h - 19:00h',
    'Infantil i Primària',
    'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&q=80&w=1000',
    'bg-red-500',
    'Ritme, coordinació i cultura popular. Ensenyem als nens a tocar el timbal i a participar en les festes del barri i l''escola.',
    'Pati interior',
    12,
    '[{"group": "Grup Únic", "days": "Divendres", "time": "17:30 — 19:00"}]'::jsonb,
    null,
    'library_music',
    false
),
(
    'Futbol',
    'Esports',
    30,
    '/mes',
    'Dimarts/Dijous, 16:30h - 18:00h',
    'Primària (1r - 6è)',
    'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&q=80&w=1000',
    'bg-green-500',
    'Entrenament tècnic i valors d''equip. Els nostres monitors fomenten el respecte, la cooperació i el joc net mentre els alumnes milloren les seves habilitats futbolístiques.',
    'Pista Poliesportiva',
    4,
    '[{"group": "A: 1r-3r", "days": "Dimarts/Dijous", "time": "16:30 — 18:00"}, {"group": "B: 4t-6è", "days": "Dimecres/Divendres", "time": "16:30 — 18:00"}]'::jsonb,
    null,
    'sports_soccer',
    false
),
(
    'Anglès',
    'Idiomes',
    30,
    '/mes',
    'Dimarts/Dimecres, 16:30h - 18:00h',
    'Primària',
    'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&q=80&w=1000',
    'bg-blue-500',
    'Reforç i ampliació de la llengua anglesa seguint el currículum escolar però amb un enfocament més comunicatiu i dinàmic.',
    'Biblioteca',
    6,
    '[{"group": "A: 1r-3r", "days": "Dimarts", "time": "16:30 — 18:00"}, {"group": "B: 4t-6è", "days": "Dimecres", "time": "16:30 — 18:00"}]'::jsonb,
    null,
    'translate',
    false
),
(
    'Patinatge',
    'Esports',
    30,
    '/mes',
    'Dimecres, 16:30h - 18:00h',
    'Primària',
    'https://images.unsplash.com/photo-1533602120417-09d5dd2bb545?auto=format&fit=crop&q=80&w=1000',
    'bg-cyan-500',
    'Equilibri i diversió sobre rodes. Aprenem tècniques bàsiques de lliscament, frenada i girs en un entorn segur.',
    'Pati de Primària',
    3,
    '[{"group": "Iniciació", "days": "Dimecres", "time": "16:30 — 18:00"}]'::jsonb,
    'Obligatori portat casc, genolleres i colzeres.',
    'sports_skating',
    false
);
